### PR TITLE
Remove/relax peer dependencies

### LINKED ISSUE #3: Relax peer dependencies
image

Does it need to have `react-three-fiber` and `three` as peer dependencies at all? It seems pretty generic, but perhaps I'm missing something.

### PR DESCRIPTION
**Pull request by axelboc**
Fix #3

### CODE REVIEW

**Comment by rijk** [comment]
@drcmda was this pushed to NPM already? When I try to `npm i use-asset` I get the following error:

```
rijk@MacBook-Pro-2020 react-subscribe-suspense % npm i use-asset@0.1.2
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-subscribe-suspense@undefined
npm ERR! Found: three@0.122.0
npm ERR! node_modules/three
npm ERR!   peer three@">=0.115" from react-three-fiber@4.2.21
npm ERR!   node_modules/react-three-fiber
npm ERR!     peer react-three-fiber@"^4.2.20" from use-asset@0.1.2
npm ERR!     node_modules/use-asset
npm ERR!       use-asset@"0.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer three@"^0.119.1" from use-asset@0.1.2
npm ERR! node_modules/use-asset
npm ERR!   use-asset@"0.1.2" from the root project
```

But I'm not sure if I'm doing something wrong :)

**Comment by rijk** [comment]
FYI, it worked with npm@6.14.8, but not with npm@7.0.2.

**Comment by drcmda** [comment]
i published it an hour ago or so. does that mean npm 7 will ERROR out on missing peers? :-S that would be crazy.

**Comment by rijk** [comment]
No worries, it worked now. I was just a bit too soon I think ;)

By the way, just published a package for Meteor subscriptions using this one: https://github.com/rijk/meteor-subscribe-suspense

**Pull request merged**
